export const REDIS_CLIENT = Symbol('REDIS_CLIENT')
export const PRISMA_CLIENT = Symbol('PRISMA_CLIENT')
export const JWT_SECRET = Symbol('JWT_SECRET')
export const RABBITMQ_TOKEN = Symbol('RABBITMQ_TOKEN')
export const EMAIL_RABBITMQ_TOKEN = Symbol('EMAIL_RABBITMQ_TOKEN')
